import Link from "next/link";
import { siteUrl } from "@/lib/config";

const apiExamples = [
  {
    title: "Publish HTML",
    value: `POST /api/publish
{
  "html": "<!DOCTYPE html><html><head><title>Launch</title></head><body>...</body></html>"
}`,
  },
  {
    title: "Publish multiple files",
    value: `POST /api/files
{
  "files": {
    "index.html": "<!DOCTYPE html>...",
    "style.css": "body { font-family: system-ui; }",
    "script.js": "console.log('ship');"
  }
}`,
  },
];

function Button({
  href,
  children,
  variant = "primary",
}: {
  href: string;
  children: React.ReactNode;
  variant?: "primary" | "secondary";
}) {
  const styles =
    variant === "primary"
      ? "bg-white text-black hover:bg-zinc-200"
      : "border border-border bg-card text-text hover:border-zinc-500";

  return (
    <a
      href={href}
      className={`inline-flex items-center justify-center rounded-full px-5 py-2.5 text-sm font-medium transition ${styles}`}
    >
      {children}
    </a>
  );
}

export default function HomePage() {
  return (
    <main className="mx-auto flex min-h-screen w-full max-w-6xl flex-col px-6 py-8 md:px-10">
      <div className="flex items-center justify-between border-b border-border/80 pb-6">
        <div>
          <p className="text-sm font-medium tracking-[0.22em] text-muted uppercase">ship</p>
          <p className="mt-1 text-sm text-muted">Pastebin for AI-generated apps.</p>
        </div>
        <Link
          href="/llm"
          className="rounded-full border border-border bg-card px-4 py-2 text-sm text-text transition hover:border-zinc-500"
        >
          API Docs
        </Link>
      </div>

      <section className="grid flex-1 items-center gap-10 py-16 md:grid-cols-[1.3fr_0.7fr] md:py-24">
        <div className="max-w-3xl">
          <p className="mb-5 inline-flex rounded-full border border-border bg-card px-3 py-1 text-xs text-muted">
            No GitHub. No Vercel setup. No auth for MVP.
          </p>
          <h1 className="max-w-2xl text-5xl font-semibold tracking-tight text-text md:text-7xl">
            Deploy AI-generated apps instantly.
          </h1>
          <p className="mt-6 max-w-2xl text-lg leading-8 text-muted md:text-xl">
            Turn HTML generated by ChatGPT, Claude, Gemini, Cursor, or any LLM into a live URL
            in seconds.
          </p>
          <div className="mt-10 flex flex-wrap gap-3">
            <Button href="/llm">View API Docs</Button>
            <Button href="#instructions" variant="secondary">
              Publish Example
            </Button>
          </div>
        </div>

        <div className="rounded-3xl border border-border bg-card p-6 shadow-soft">
          <div className="mb-6 flex items-center justify-between">
            <div>
              <p className="text-sm text-muted">Example output</p>
              <p className="text-lg text-text">{`${siteUrl}/abc123`}</p>
            </div>
            <div className="h-3 w-3 rounded-full bg-white/70" />
          </div>
          <div className="space-y-3 text-sm leading-6 text-muted">
            <p>1. LLM generates HTML.</p>
            <p>2. ship stores it in cheap object storage.</p>
            <p>3. The page is live on the internet immediately.</p>
          </div>
        </div>
      </section>

      <section className="grid gap-6 border-t border-border/80 py-12 md:grid-cols-2">
        <div className="rounded-3xl border border-border bg-card p-6">
          <p className="text-sm text-muted">What it is</p>
          <h2 className="mt-2 text-2xl font-semibold text-text">Vercel for AI prototypes</h2>
          <p className="mt-4 text-sm leading-7 text-muted">
            ship makes a generated app instantly shareable by giving it a short, permanent URL.
          </p>
        </div>
        <div className="rounded-3xl border border-border bg-card p-6">
          <p className="text-sm text-muted">Why it matters</p>
          <h2 className="mt-2 text-2xl font-semibold text-text">Optimized for chats</h2>
          <p className="mt-4 text-sm leading-7 text-muted">
            Short links are easy to drop into ChatGPT, X posts, YC applications, and live demos.
          </p>
        </div>
      </section>

      <section id="instructions" className="border-t border-border/80 py-12">
        <div className="flex flex-col gap-3">
          <p className="text-sm text-muted">Instructions for AI Models</p>
          <h2 className="text-3xl font-semibold text-text">Copy this block into your agent prompt</h2>
          <p className="max-w-3xl text-sm leading-7 text-muted">
            This section is intentionally plain and machine-readable for ChatGPT, Claude, Gemini,
            Cursor, Windsurf, and future agents.
          </p>
        </div>

        <div className="mt-6 space-y-4">
          <pre className="overflow-x-auto rounded-3xl border border-border bg-black/30 p-5 text-sm leading-7 text-text">
{`To publish an HTML application:

POST ${siteUrl}/api/publish

Content-Type: application/json

{
  "html": "<!DOCTYPE html>...</html>"
}

Response:
{
  "id": "abc123",
  "url": "${siteUrl}/abc123"
}

If a user asks you to publish an HTML page using ship,
send the generated HTML to the endpoint above and return the URL.`}
          </pre>

          <div className="grid gap-4 md:grid-cols-2">
            {apiExamples.map((example) => (
              <div key={example.title} className="rounded-3xl border border-border bg-card p-5">
                <p className="mb-3 text-sm text-muted">{example.title}</p>
                <pre className="overflow-x-auto text-xs leading-6 text-text">{example.value}</pre>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="grid gap-6 border-t border-border/80 py-12 md:grid-cols-3">
        <div className="rounded-3xl border border-border bg-card p-6">
          <p className="text-sm text-muted">Storage</p>
          <p className="mt-3 text-lg text-text">Cloudflare R2 first</p>
          <p className="mt-3 text-sm leading-7 text-muted">
            Raw HTML stored as objects. Cheap enough for thousands of pages.
          </p>
        </div>
        <div className="rounded-3xl border border-border bg-card p-6">
          <p className="text-sm text-muted">Safety</p>
          <p className="mt-3 text-lg text-text">Validation and throttling</p>
          <p className="mt-3 text-sm leading-7 text-muted">
            Enforced size limits, basic sanitization, and per-IP rate limiting.
          </p>
        </div>
        <div className="rounded-3xl border border-border bg-card p-6">
          <p className="text-sm text-muted">Roadmap</p>
          <p className="mt-3 text-lg text-text">Moderation-ready</p>
          <p className="mt-3 text-sm leading-7 text-muted">
            The API is structured so moderation, reporting, and richer review can slot in later.
          </p>
        </div>
      </section>
    </main>
  );
}
